# Generated by Django 2.1.15 on 2023-04-12 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CafeCoffeeDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coffeeName', models.CharField(max_length=200)),
                ('fName', models.CharField(max_length=300)),
                ('address', models.TextField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
